Fix missing async
const addDetailResult = await db.query(
                                     ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules